services:
  postgres:
    container_name: user_auth_db
    image: postgres:latest
    environment:
      POSTGRES_USER_FILE: /run/secrets/DB_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/DB_PASS
      POSTGRES_DB: user_auth_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - grm
    secrets:
      - DB_USER
      - DB_PASS
    restart: unless-stopped

  authentication_app:
    container_name: authentication_api
    image: authentication_api
    secrets:
      - DB_URL
      - DB_USER
      - DB_PASS
      - JWT_TOKEN
    ports:
      - "1010:1010"
    networks:
      - grm
    depends_on:
      - postgres

  pgadmin:
    container_name: db_manager
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: bonganialfred@live.co.za
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/DB_PASS
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "1020:80"
    networks:
      - grm
    secrets:
      - DB_PASS

volumes:
  postgres:
    driver: local

networks:
  grm:
    driver: bridge

secrets:
  DB_URL:
    file: /home/ghostkeys/.db/db_url.txt
  DB_USER:
    file: /home/ghostkeys/.db/db_user.txt
  DB_PASS:
    file: /home/ghostkeys/.db/password.txt
  JWT_TOKEN:
    file: /home/ghostkeys/.db/json_token.txt
