server:
  port: 1010
spring:
  # Data source configuration
  datasource:
    url$: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

# Security configuration
security:
  jwt:
    secret-key: ${JWT_TOKEN}
    expiration: 86400000
    refresh-token:
      expiration: 604800000